name: Deploy App

on:
  push:
    tags:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/alta-golang-capstone:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker stop golang-app-container
            sudo docker rm golang-app-container
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/alta-golang-capstone:${{ github.ref_name }}
            sudo docker run -d --network=host --restart=always -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -e SMTP_SERVER=${{ secrets.SMTP_SERVER }} -e SMTP_PORT=${{ secrets.SMTP_PORT }} -e SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} -e CREDENTIALS=${{ secrets.CREDENTIALS }} --name golang-app-container ${{ secrets.DOCKERHUB_USERNAME }}/alta-golang-capstone:${{ github.ref_name }}
